#%RAML 1.0 Library
types:
  add_new_case:
    description: creating new case
    type: object
    properties:
        owner_Id:
          description: owner Id
          type: string
          required: false
       
        priority:
          description: priority of the case
          type: string
          required: false
        
        description:
          description: description of the case
          type: string
          required: false
    
        status:
          description: status of the case
          type: string
          required: false
        subject:
          description: subject of the case
          type: string
          required: false
        sync_update_record_to_sfdc:
          description: updating new case
          type: boolean
          required: false
        sync_new_record_to_sfdc:
          description: creating new case
          type: boolean
          required: false
        external_id:
          description: external id of the case
          type: integer
          required: false     
  case_added_response:
    description: Pick Release Response
    properties:
      is_success :
        description: Success
        type: boolean
        required: true
      id:
        description: result
        type: integer
        required: false
     
      result :
        description: 
        type: array
        required: false
      
      errors:
        type: array
        description: Errors
        items:
          properties:
            error_code:
              type: string
              description: Unique error code
              required: false
            error_message:
              type: string
              description: Indicates a message associated with its error code.
              required: false